Fixed backward incompatibility for engines.
- Many engines rely on being able to join directories to the Rails root:

    Rails.root.join('somedir')

- This was now impossible because Rails.root returned a String:

    NoMethodError: undefined method `join' for "/code/myrailsapp":String

- This was broken in 93641868005b6f2e791806e1d22a1309d15d155a